spring:
  data:
    mongodb:
      database: xsc_pk_201904_pt

xsc:
  aid:
    server-base-url: http://localhost:8086/openeva
    x-auth-code: GOD_BLESS_ME
    test-ids: 82109c34-690d-4e57-ae39-3f8306505fbb, bc16450c-6a3f-42c3-9faa-620199f7f43f, 19190f23-6f94-497c-aab8-3a22bdbc8f58, 77ef321a-c536-4146-b7ea-fedaa4136a61
    #    server-base-url: https://api.xueliceping.com/openeva
    #    x-auth-code: b3d0369a-06b3-4cd8-8000-786765e63e46
    #    test-ids: 1d42585b-7da4-4385-add3-d90511ac7852, fb803090-34a1-49e8-9bae-5754f64ccfbe, 86e96a7b-05c2-448f-a398-04c4960371d8

    ticket-gen-path: /admission-tickets/test/{test-id}
    fid-to-uid-path: /uids/fid/{foreign-id}
    tickets-by-uid-path: /admission-tickets/user/{user-id}
    single-test-path: /tests/{test-id}
    login-path: /login/vcode
    paper-path: /login/papers/user/{user-id}
    answer-post-path: /answers/test/{test-id}/user/{user-id}
    answersheet-post-path: /answer-sheets/{ticket-id}

    pressure-foreign-id-prefix: 'FOREIGN_USER:TEST:PRESSURE:'
    pressure-user-count: 500
    pt-leading-user-index: 0
    pt-user-count: 1
    answer-submission-repeat: 1
    god-vcode: 999999
    # unit=>second
    exam-duration: 300
    # unit=>second
    mock-client-trigger-window-span: 10
    # 最后一个答卷提交窗口期的跨度
    # unit=>second
    final-as-submission-window-span: 50
    test-time-deviation: 0.2
    user-level-count: 5
    answers-count-ratio-gap: 0.1
    submission-delay-deviation: 0.2

    pt-schedule-cron: '0 44 * * * ?'